=== saiprasaad/Java_Lab_Exercises/email_sending_using_SAX/target/classes/items.dtd
<!ELEMENT items (item+)>
<!ELEMENT item (sno,itemname,price,quantity,amount)>
<!ELEMENT sno (#PCDATA)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== saiprasaad/Java_Lab_Exercises/XMLtoPDF/src/items.xml
<!DOCTYPE items SYSTEM "items.dtd">
<items>
	<item>
		<sno>1</sno>
		<itemname>DairyMilk</itemname>
		<price>50</price>
		<quantity>3</quantity>
		<amount>150</amount>
	</item>
	<item>
		<sno>2</sno>
		<itemname>Pringles Chips oru packet</itemname>
		<price>100</price>
		<quantity>2</quantity>
		<amount>200</amount>
	</item>
</items>
